#include "arduino_secrets.h"

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/61d00fa6-ec7c-414f-8e1c-12ec937ae793 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float temp;
  int lightlevel;
  bool occupancy;
  bool relay;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <DHT.h>
#define DHTPIN 32           // GPIO 32 for DHT22 sensor
#define DHTTYPE DHT22       // DHT22 sensor type
#define PIRPIN 34           // GPIO 34 for PIR sensor
#define LDRPIN 35           // GPIO 35 for LDR sensor (analog input)
#define RELAYPIN 25


// Initialize DHT sensor
DHT dht(DHTPIN, DHTTYPE);

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  dht.begin();
  pinMode(PIRPIN, INPUT);
  pinMode(LDRPIN, INPUT);
  pinMode(RELAYPIN, OUTPUT);
  digitalWrite(RELAYPIN, LOW);
  Serial.println("Relay OFF - HVAC Lighting OFF");

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  Serial.println("Smart Energy Management System Initialized");
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information youâll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  temp = dht.readTemperature();
  occupancy = digitalRead(PIRPIN);
  lightlevel = analogRead(LDRPIN);
  onRelayChange();
  delay(4000);
}


/*
  Since Temp is READ_WRITE variable, onTempChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTempChange()  {
  float temperature = dht.readTemperature();
  
  if ( !isnan(temperature)) {
    Serial.println("Error reading DHT22 sensor");
    return;
  } else {
    Serial.print("Temperature: ");
    Serial.print(temperature);
    Serial.println(" Â°C");
  } 
}

/*
  Since Lightlevel is READ_WRITE variable, onLightlevelChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightlevelChange()  {
 // Read and update ambient light from LDR sensor
  int lightLevel = analogRead(LDRPIN);
  lightLevel = lightLevel;
  Serial.print("Light Level: ");
  Serial.println(lightLevel);
}

/*
  Since Occupancy is READ_WRITE variable, onOccupancyChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onOccupancyChange()  {
  bool motionDetected = digitalRead(PIRPIN);
  occupancy = motionDetected;
  Serial.print("Occupancy: ");
  Serial.println(occupancy ? "Detected" : "Not Detected");
}

void onRelayChange()  {
  if (occupancy  == true && lightlevel < 500) {
    digitalWrite(RELAYPIN, HIGH);
    Serial.println("Relay ON - Activating HVAC Lighting");
  } else {
    digitalWrite(RELAYPIN, LOW);
    Serial.println("Relay OFF - Deactivating HVAC Lighting");
  }
}
